html css completion
salvik21/Project1 pull request #7
Opened 2021-10-16 15:46 UTC by salvik21

2021-10-18 12:56 UTC, YuraLeo94 requested changes
The gallery does not match the [design ](https://github.com/Hetachi/FrontEndTraining/blob/master/visuals/Renome%20Template/!!!Mobile/One%20Page/Mobile_one%20page.psd)- fix it please
![image](https://user-images.githubusercontent.com/71021726/137733419-7c895b54-298e-4ace-93d9-96412ae26009.png)
Need space between icons looks [design ](https://github.com/Hetachi/FrontEndTraining/blob/master/visuals/Renome%20Template/!!!Mobile/One%20Page/Mobile_one%20page.psd)please
![image](https://user-images.githubusercontent.com/71021726/137733729-1afadf7a-c971-4811-b930-52cb2bbd1cc8.png)
Why do you use new font for the logo in the footer?  Looks please difference between the logo in the header and footer in the design. Your old logo font from the header will be fine for the footer logo.
![image](https://user-images.githubusercontent.com/71021726/137734007-4744cc71-3dcd-4bcb-89b4-aebd397a3d29.png)

2021-10-18 12:56 UTC, YuraLeo94 commented on style.css
> +  background-color: rgb(250, 250, 250);
For what reason are you using here, above and below `rgb`?

2021-10-18 12:56 UTC, YuraLeo94 commented on style.css
> +  margin: 10px 10px;
can do shorter ` margin: 10px`

2021-10-18 12:56 UTC, YuraLeo94 commented on style.css
> +  margin: 10px 0;
change please on next size `margin: 15px 0 30px;`

2021-10-18 12:56 UTC, YuraLeo94 commented on style.css
> +  margin-bottom: 10px;
change please on next size `margin: 0`, don't need `margin` for this element

2021-10-18 12:56 UTC, YuraLeo94 commented on style.css
> +  padding: 30px 0;
change please on next size `padding: 70px 0;`

2021-10-18 12:56 UTC, YuraLeo94 commented on style.css
> +  margin-top: 30px;
here don't need `margin-top`, since padding give you necessary space

2021-10-23 22:07 UTC, salvik21 reviewed
![Снимок](https://user-images.githubusercontent.com/86931898/138573032-b6ad4843-2ed8-49cf-a2d1-cd993186b8f4.JPG)

2021-10-23 22:09 UTC, salvik21 reviewed
![Снимок2](https://user-images.githubusercontent.com/86931898/138573105-0d870db4-e148-4598-ac6c-f81854ba48ef.JPG)

2021-10-25 10:27 UTC, YuraLeo94 requested changes

2021-10-25 10:27 UTC, YuraLeo94 commented on style.css
> +  margin: 30px 5px 50px 5px;
Change please at the `margin: 0 5px` it will be more close to the design.

2021-10-25 11:40 UTC, YuraLeo94 approved these changes

2021-10-25 11:42 UTC, merged