added JS code to cart menu and update html code
salvik21/Project1 pull request #8
Opened 2022-01-15 20:44 UTC by salvik21

2022-01-15 21:39 UTC, YuraLeo94 requested changes

2022-01-15 21:39 UTC, YuraLeo94 commented on index.html
> +           </div>
It's should be in the nav block.

2022-01-15 21:39 UTC, YuraLeo94 commented on index.html
> +              <div id="cart-menu__button"><a target="__blank" href="" >$44.50</a></div>
When you need assign style more than one element use class.

2022-01-15 21:39 UTC, YuraLeo94 commented on index.html
> +              <div id="cart-menu__button"><a target="__blank" href="" >$44.50</a></div>
Please change "id" on the "class"

2022-01-15 21:39 UTC, YuraLeo94 commented on index.html
> +              <div id="cart-menu__button"><a target="__blank" href="" >$44.50</a></div>
Also, why do you need `target="__blank"` here? When you click view cart in an online store, it open a new tab, or it open the cart in the same tab?

2022-01-15 21:39 UTC, YuraLeo94 commented on index.html
> +           <div id="nav__cart-menu">
think it's better to add the "showMenu_off" class here.

2022-01-15 21:39 UTC, YuraLeo94 commented on java.js
> +cartMenu.classList.add("showMenu_off");
you can add it in html code

2022-01-15 21:39 UTC, YuraLeo94 commented on java.js
> +const navCart = document.querySelector(".nav__cart");
Better use id instead class for this purpose

2022-01-15 21:39 UTC, YuraLeo94 commented on java.js
> +function Cart() {
I think name `toggleCart` will tell more than just `Cart`

2022-01-15 21:39 UTC, YuraLeo94 commented on java.js
> +}
I not found where you use this function? Do you need this function?

2022-01-15 21:39 UTC, YuraLeo94 commented on style.css
>  }
Better add more specific name `cart-menu--on` `cart-menu--off` or `show-cart-menu--on` `show-cart-menu--off`.

2022-01-15 21:39 UTC, YuraLeo94 commented on style.css
>  }
Also don't forget about naming with BEM

2022-01-24 16:16 UTC, YuraLeo94 requested changes
Sorry, forgot to write before. A better name for a file with `.js` extension will be what is inside this file. In the current case, it can name like `cart.js`, since you do functionality for cart, not `java`. **Java** is a _programming language_.
Also when you will start to implement functionality for the menu and carousel you can create two files `menu.js` and `carousel.js` and etc.

2022-01-24 16:16 UTC, YuraLeo94 commented on java.js
>    else{
space `else {`

2022-01-24 16:16 UTC, YuraLeo94 commented on java.js
> +  if(cartMenu.classList.contains("nav__cart-menu--on")){
also space `if (cartMenu.classList.contains("nav__cart-menu--on")) {`

2022-01-24 16:16 UTC, YuraLeo94 commented on java.js
>    else{
You can try the next key combination `alt+shift+f`, hope it will help you do auto-correction for this file.

2022-01-24 16:21 UTC, CoobQ commented on java.js
> +function toggleCart() {
Your function is called toggle but it doesn't toggle. please check https://www.w3schools.com/howto/howto_js_toggle_class.asp

2022-01-24 17:55 UTC, YuraLeo94 approved these changes

2022-01-27 18:30 UTC, merged